//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_Shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSepatu
    {
        public string id_sepatu { get; set; }
        public string id_kategori { get; set; }
        public string id_supplier { get; set; }
        public string id_garansi { get; set; }
        public string nama_sepatu { get; set; }
        public int stock { get; set; }
        public decimal harga_beli { get; set; }
        public decimal harga_jual { get; set; }
        public byte[] gambar { get; set; }
        public Nullable<int> minimum_stock { get; set; }
        public int status { get; set; }
    }
}
